### ISSUE TITLE
 Possible pending tails after 1.0.0 release

### ISSUE THREAD

**Issue by puzrin** [nodeca/navit#1]
**If you need one of missed features, just post a message to let us know.**

Here we collect features, not included in first release due timeline restrictions or mad by nature
- `.test.*` improvements
  - Testing against regex should returm better message (now "false !== true")
  - `test.evaluate` should show real value when not `true`
  - check all similar places when details can be lost
  - Probably we could pop useless data from assertion `.stack` (no need to trace navit internals when users write tests for applications).
- Option to disable redirects in `.open()`.
  - is it useful?
  - is it possible with SlimerJS

**Comment by puzrin** [comment]
[ ] `option.prefix` - useful

**Comment by puzrin** [comment]
Probably missed methods
- `.fill()` for forms, as in CasperJS
  - We don't need it (`.type` is ok), but probably worth to implement
  - Signature: `.do.fill(selector, obj [, submit])`
- `.pdf()`
- `.get.response()`
  - is it useful? We already can get/test separate properties (status, body, headers). Probably, more low lever testing is better to do with `supertest` and so on.
- `.test.class(selector, name)`
- ? test css style

**Comment by puzrin** [comment]
Other features:

- tabs api

**Comment by puzrin** [comment]
- set/get/test attribute missed

**Comment by monolithed** [comment]
Would be nice to implement the `.fill`. 

``` js
.open('/user/login')
.type('[name="email"]', accounts.regular.email)
.type('[name="password"]', accounts.regular.password)
.click('[data-name="submit"]')
```

``` js
.open('/user/login')
.fill('[name="form"]', {
    email   : accounts.regular.email,
    password: accounts.regular.password
}, true)
```

The second example is more structural.
And what about forms without any submit buttons?

**Comment by puzrin** [comment]
@monolithed  I'd like to get form fill as PR - it does not needs internals change but require some time to implement. If someone decide to help - i will create a ticket to discuss signatures.

**Comment by monolithed** [comment]
@puzrin, I'm trying to test `submit` 

I have a simple test to submit form. Test fails after asserting exception on the same url.

https://github.com/monolithed/navit/commit/7ba5cbade8ea3e441a8f9b41aac5094d474e8485

Actual:

```js
assert.equal(url, 'http://localhost:17345/test/fixtures/do/back.html'); 
// url — 'http://localhost:17345/test/fixtures/do/submit.html'
```

Expected:

```js
assert.equal(url, 'http://localhost:17345/test/fixtures/do/back.html'); 
// url — 'http://localhost:17345/test/fixtures/do/back.html'
```

**Comment by puzrin** [comment]
Please, post it in separate issue. This one is for tracking postponed ideas, not for discussions.

**Comment by puzrin** [comment]
Close as outdated & partially done. Therest is in #38
