### ISSUE TITLE
Custom methods?

### ISSUE THREAD

**Issue by inca** [nodeca/navit#13]
Hi guys,

Is there any preferred way to add custom methods to Navit instances? Currently I'm sticking with `browser.do.magic = function() { return this }`, but I'm not sure whether this is considered a bad practice.

TIA

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/blob/master/lib/index.js#L62

Use `.registerMethod()`, it will care about proper merge into properties tree

**Comment by inca** [comment]
Ah, brilliant! Huge thanks, Vitaly!

**Comment by puzrin** [comment]
Updated readme. Send PR, if more fixes needed.
