### ISSUE TITLE
Run without closing tabs

### ISSUE THREAD

**Issue by inca** [nodeca/navit#14]
Greetings again,

I'm currently trying to figure out a way to establish a scenario-based testing, where each `describe` section corresponds to a single interaction scenario with multiple steps. `mocha-steps` is doing a great job ensuring that further steps won't fire after bail; however, each execution of Navit is performed in a clean tab, so no client-side context can be preserved between test cases.

Something like this would be desired:

``` js
before(function (done) {
  browser.open('/url')
    .do.magic(/*...*/)
    .runQueue(done);
});

step(function(done) {
  browser
    .do.something()
    .get.something(function(smth) {
    /* assert it */
    })
    .runQueue(done); 
});

step(function(done) {
  browser
    .do.somethingElse()
    .get.something(function(smth) {
    /* assert it */
    })
    .runQueue(done);
});
```

Without this feature I can't effectively control the granularity of test cases.

Is there a way to tell Navit not to destroy tabs when running? Or is there other way around?

Thanks!

**Comment by puzrin** [comment]
In theory it's a bad idea to passe page content between suites, and before/after exists to solve this problem - do all preparations. We use additional helpers & `.afterOpen()` to simplify setup in our case: https://github.com/nodeca/nodeca.core/blob/master/lib/test/navit_plugins.js

I understand that other programmers can have different opinion on this problem, and i'm open to suggensions about API update.

What kind of content do you need to pass between pages? Cookies?

**Comment by puzrin** [comment]
Could you give links with examples of real scenario-based tests? Probably, i'm not familiar with some useful cases.

**Comment by inca** [comment]
It's not about the information passing between the steps, it's more about maintaining page state for each test case (e.g. opening a page, clicking around, filling something out, etc., etc.), which is somewhat essential for single page applications.

I was able to achieve the desired effect by introducing another method (which is essentially a copy of `run` with some corrections):
1. The task at [index.js#161](https://github.com/nodeca/navit/blob/master/lib/index.js#L161) is modified to check if `__page__` is already opened:
   
   ``` js
   // Init page if not intialized or already closed
   function (next) {
     if (self.__page__) {
       next();
       return;
     }
     self.__initPage__(next);
   },
   ```
2. The last task which closes the tabs starting at [index.js#171](https://github.com/nodeca/navit/blob/master/lib/index.js#L171) is removed.

With this method in place (I called it `runSteps`, but we need to find it a better name) one can implement following suite:

``` js
describe('Scenario', function () {

  before(function (done) {
    browser
      .do.login()
      .do.open('/page')
      .runSteps(done);
  });

  step('do something', function (done) {
    browser
      .do.wait(function () {
        return document.title == 'My app';
      })
      .runSteps(done);
  });

  step('assert something', function (done) {
    browser
      .get.evaluate(function () {
        return true;
      }, function (result) {
        assert.equal(result, true);
      })
      .runSteps(done);
  });

  after(function (done) {
    browser.close(done);
  });

});
```

Note how I don't repeat the `open` and `login` steps (even if it would take a single line of code in each case).
It is important that the page state is maintained between test cases, not reloaded each time.

**Comment by inca** [comment]
Not sure if it's worth adding that to the library, however, since my case could be not that widespread.

I am pretty happy with the ability to register custom methods; my only concern is that I have essentially copied the internal stuff from Navit, which is a subject to change even in patch releases.

Maybe we could at least factor out something (e.g. `runQueue`, `initPage` or something) so that I could build up this method using public API?

**Comment by inca** [comment]
As for the "bad practice", I don't see nothing wrong with this approach as long as you are aware about how things work (i.e. you must ensure that the page is closed, etc).

**Comment by puzrin** [comment]
Well, what should be changed in API to fit your needs ? I see 3 possibilities:
1. `.runSteps()`, as you did - similar to `.run()`, but will not close browser & tab.
2. `keepTab: true` in constructor - don't like it, because too global
3. Never close tabs until browser open - don't know side effects. Any conflicts possible with another use types?

What do you think?

**Comment by inca** [comment]
Ideally, I'd prefer the 1st, although the `runSteps` name is somewhat confusing and awkward. I can send PR tomorrow, and I'll try to think of a better name for this method in a meantime.

**Comment by puzrin** [comment]
Will (3) have side effects? It looks more simple to cut code instead of adding more.

**Comment by inca** [comment]
Not with my use cases, no. I always close instances explicitly, so I guess it'll work fine for me.

**Comment by puzrin** [comment]
At first glance, we need this change:
1. Don't automate tabs close, it seems to be design error.
2. Add `.tab.first`, `tab.last` & `tab.close` + autocreate tab on `.open` if none exists

If looks ok, i'll ask @Kirill89 to do it tommorow.

**Comment by inca** [comment]
Thanks! It's truly a pleasure doing business with you :)

**Comment by puzrin** [comment]
Revisited existing api. That's a final things to do:
- don't close tabs
- make sure `.tab.switch()` accepts negative values (count from the end like `slice()`)

/cc @Kirill89

**Comment by inca** [comment]
Could I also suggest to add a check if `__page__` already initialized?

``` js
  if (self.__page__) {
    next();
    return;
  }
  self.__initPage__(next);
```

**Comment by puzrin** [comment]
Sure.

**Comment by puzrin** [comment]
Postponed for tomorrow - some unexpected ugly bugs. See progress in dev branch.

**Comment by puzrin** [comment]
It seems our problem could be caused by this bug https://github.com/detro/ghostdriver/issues/328.

Tab close/open seems to help.

**Comment by puzrin** [comment]
Fixed, but needs testing. @inca please check that phantomjs don't crash in your existing tests after this change. The most interesting are tests with multiple `.open` & `.wait`.

If problem exists, may be we should add `keepTabs` config option, disabled by default.

**Comment by inca** [comment]
Awesome! I can confirm that everything works like a charm with this new `run` implementation. Specifically, I have a test case with two `open`, `reload` and a dozen of `wait`s, everything is intact.

Thanks!

**Comment by puzrin** [comment]
2 `open` is too few. We had to add kludge in our tests https://github.com/nodeca/navit/blob/master/test/do.js#L284. Don't know is it something specific or not.

Also note, we are splitting all engine options to secondary constructor param https://github.com/nodeca/navit/issues/9#issuecomment-117066189. It's already in master. In other case - too many conflicts between phantomjs & slimerjs.

**Comment by inca** [comment]
OK, thanks, I'll keep that in mind.

**Comment by inca** [comment]
BTW, I didn't say it correctly: I was talking about one test case out of a suite of ~100 test cases. Although, I can't say for sure if I can reproduce these problems since I don't open/reload pages very often (around 20 `open`s per entire suite).
