### ISSUE TITLE
get/test sugar for inputs/selects?

### ISSUE THREAD

**Issue by inca** [nodeca/navit#19]
How do you retrieve or assert the `element.value`? I mean, we have sugar methods that allow you to type, select values and check/uncheck checkboxes, but how do we assert the job we have done? Doing this with `.get.evaluate` or similar client-side JS is fine, but having sugar API wouldn't hurt.

**Comment by puzrin** [comment]
https://github.com/nodeca/navit#assertions-test--test. It should mirror all get.\* method without couple of exclutions. If you can get.something, then you can test.something.

get.text / get.attribute will not help?

**Comment by puzrin** [comment]
Ups... that have no relation to lazy evaluation. Let's leave open.

**Comment by inca** [comment]
Both `get.text` and `get.attribute` yield empty string when called on inputs, currently the only solution available is a longer one:

``` js
.get.evaluate(function () {
  return document.querySelector('input').value;
}, function (value) {
  // do stuff
})
```

**Comment by puzrin** [comment]
I think i've missed it. Expected that `.get.attribute('selector', 'value', ...)` should work but had no chance to test. Seen those methods in nightmare and other libs, but could not unterstood their use, and finally dropped.

**Comment by puzrin** [comment]
2 stupid questions to clarify api change:
-  is `.value` the only way to get input's content?
-  is `.value` needed for input only or will be useful for something else?

**Comment by inca** [comment]
Yes, `.value` is the correct way of retrieving the text of `input`s and `textarea`s, and the selected option value in `select`s.

**Comment by puzrin** [comment]
Done
