### ISSUE TITLE
Should tests allow optional callback?

### ISSUE THREAD

**Issue by puzrin** [nodeca/navit#2]
Probably, saving `.run()` call is bad idea or over-engeneering. This also makes teardown flag a bit inconsistent.

I tend to remove this feature. If anyone has example why optional callbacks in tests should stay intact - let me know.

**Comment by inca** [comment]
Hi, Vitaly,

Huge thanks for a :gem: piece of software engineering!

:+1: for removing callbacks in assertions: since I came from a bit of Nightmar'ish background, I tend to queue things up and then call `run`.

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/commit/38e07ca26db6c17da39992352b1e6271bbaaf9c6
