### ISSUE TITLE
.test.evaluate.deepEqual ?

### ISSUE THREAD

**Issue by puzrin** [nodeca/navit#23]
Now this pattern is used quite often:

``` js
.get.evaluate(function () {
  ...
  return [ a, b, c ];
}, function (data) {
  assert.deepEqual(data, ...)
});
```

It could be more compact. Something like

``` js
.test.evaluate.deepEqual(function () {
  // code to get object
  return result;
}, obj)
```
1. Need good function name.
2. Do we need something except (evaluate + deepEqual) and (evaluate + notEqual)?

**Comment by MaarekElets** [comment]
To me .test.deepEqual would make sense with the not being .test.not.deepEqual. . I'm not sure if it is absolutely required that the fact that it calls evaluate is reflected in the API name as long as the documentation makes it clear that the values to compare are retrieved in browser scope using evaluate.

**Comment by puzrin** [comment]
`.test.deepEqual` will be very confusing IMHO.
- it's not clear that it compare result of `.evaluate`
- it will conflict with another methods, if you decide to add more tests like equal, lt, gt and so on.

**Comment by MaarekElets** [comment]
Given that (and setting aside my ingrained C# worldview I'm trying to eliminate where functions really don't allow properties) I don't see any issues with .test.evaluate.deepEqual and I would presume .test.evaluate.not.deepEqual. It would also establish an api location for other evaluate based tests like the ones you mentioned. 

Going back to the 2nd question. It does seem to me the inclusion of deepEqual would logically point to the inclusion of .eq, .lt, and .gt.

**Comment by puzrin** [comment]
Problem with API is how to avoid messy crap with methods. That's why i try to avoid adding "logical" things, only "really required" added. That's why lt/gt still do not exists - nobody showed real use cases yet.

This ticket is to collect stat, how often people use (evaluate + assert) in pair.

**Comment by puzrin** [comment]
Close - outdated, still no actual demands.
