### ISSUE TITLE
More info about best practices with navit

### ISSUE THREAD

**Issue by monolithed** [nodeca/navit#25]
Are there any best practices for reporting and running tests with navit? 
I mean examples with Mocha and Karma...

**Comment by puzrin** [comment]
Targets are medium projects, when it's comfotable to do everything from single process - init server db & kick client page for example. In theory, that should not be done for pure unit tests, and you have to mock everything to run browser tests in isolated env. But practice is different :).

So:
- If you need to test all browsers, karma will be preferable (and more difficult)
- If you need to test that project "just works" (when phantom or slimer are enougth) - navit will save your time.

Navit does not force you to use mocha, but it you like - here are examples https://github.com/nodeca/navit/tree/master/test. Also, here you can see how we setup additional helpers for nodeca https://github.com/nodeca/nodeca.core/blob/master/lib/test/navit_plugins.js

Reasons why we did navit:
- simplify setup
- speedup tests writing

It's not silver bullet, but when you like to do everything from the single process - it helps.

**Comment by monolithed** [comment]
I got it, thanks

**Comment by puzrin** [comment]
In far future, it's possible to replace underlying protocols with webdriver. That will allow to run tests at selenium farms. But that requires significant internals change, and webdriver support in phantom/slimer is not perfect. So, i prefer to wait now.
