### ISSUE TITLE
Could not set SlimerJS engine

### ISSUE THREAD

**Issue by monolithed** [nodeca/navit#26]
I [found](https://github.com/nodeca/navit/issues/9) a way to use slimerjs:

``` js
let browser = require('navit')('slimerjs');
```

``` js
let Navit = require('navit');
let browser = new Navit('slimerjs');
```

No one works as expected.

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'phantomjs'
```

How to turn on SlimerJS?

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/blob/master/test/api.js#L20

You need to pass `engine` option (name or path). Seems that was missed in doc

**Comment by monolithed** [comment]
Thanks!

**Comment by puzrin** [comment]
`browser = navit({ engine: require('slimerjs').path });`

**Comment by monolithed** [comment]
`{engine: 'slimerjs}` works fine for me, thanks

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/blob/master/lib/index.js#L34-L38 here is implementation. It accepts name only, sorry for confusion.
