### ISSUE TITLE
Page loading timed out

### ISSUE THREAD

**Issue by monolithed** [nodeca/navit#27]
``` js
let Navit = require('navit');

let browser = new Navit;

browser
    .open('http://mail.ru')
    .wait('body')
    .run(error => {
        console.log('Succeeded');
    })
;
```

```
{ [NavitError: page loading timed out] name: 'NavitError', message: 'page loading timed out' }
```

What's wrong?

**Comment by monolithed** [comment]
I've the same problem with slimerjs engine

**Comment by puzrin** [comment]
Hm, there are no needs for such wait after open. But question is good.

I think, problem is that we use jquery for selectors, and it skips root-level tags. Probably, we should add `.addBack()` to allow select `body` and `head`. Is it necessary?

**Comment by monolithed** [comment]
Actually, I've the same problem with other selectors :(

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/blob/master/test/do.js#L39-L100

May be server response problems? Those features are covered with tests

**Comment by monolithed** [comment]
Hm. I've already tested at localhost and got the following:

```
{ [NavitError: 'do.wait' timed out] name: 'NavitError', message: '\'do.wait\' timed out' }
```

(

**Comment by monolithed** [comment]
Is there any log file?

**Comment by puzrin** [comment]
``` js
var Navit = require('navit');

var browser = new Navit;

browser
    .open('http://mail.ru')
    .wait('body')
    .run(error => {
        console.log('Succeeded', error);
    })
;
```

Just tested, returned error = undefined (success).

Debug info is here https://github.com/nodeca/navit#debug

**Comment by monolithed** [comment]
It's strange.... 

```
➜ export DEBUG=navit; node account/views/user/login/tests.js 
  navit do.open('http://mail.ru') +0ms
Succeeded { [NavitError: page loading timed out] name: 'NavitError', message: 'page loading timed out' }
```

At the localhost I see a white page :)

**Comment by puzrin** [comment]
Which node do you use? That's in 4.2.2:

```
 DEBUG=navit node test.js 
  navit do.open('http://mail.ru') +0ms
  navit do.wait() +882ms
Succeeded undefined
```

Try `curl http://mail.ru`, may be some firewall limits in your network and so on. Or try your tests with another hosts.

**Comment by monolithed** [comment]
```
➜ node -V
5.8.23
```

May be you're right, I'l try later at home network

**Comment by puzrin** [comment]
https://github.com/nodejs/node/blob/master/CHANGELOG.md#2015-12-16-version-530-stable-cjihrig

Latest 5.x branch is 5.3.0. I don't know what it 5.8.23 also it displays version with `node -v`, not uppercase `V`

**Comment by monolithed** [comment]
Oh, sorry — .nvm/versions/node/v5.3.0/bin/node

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/blob/master/.travis.yml#L3-L5

at least, test are passing in all major node versions. I tend to think that's a network issue. Also i was not correct, we don't use jquery for selectors.

**Comment by monolithed** [comment]
Oh, I cannot replicate at the moment. I'll look for the problem
