### ISSUE TITLE
Refusing to install navit as a dependency of itself

### ISSUE THREAD

**Issue by dimti** [nodeca/navit#33]
`$ npm install navit --save`
`npm ERR! Linux 4.3.3-2-ARCH`
`npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "navit" "--save"`
`npm ERR! node v6.2.0`
`npm ERR! npm  v3.9.2`
`npm ERR! code ENOSELF`

`npm ERR! Refusing to install navit as a dependency of itself`
`npm ERR!`
`npm ERR! If you need help, you may report this error at:`
`npm ERR!     <https://github.com/npm/npm/issues>`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /var/www/navit/npm-debug.log`

**Comment by puzrin** [comment]
That's something local. Try again. Can't reproduce in node 4 & node 6
