### ISSUE TITLE
Add an option to give a path to the PhantomJS executable

### ISSUE THREAD

**Issue by medemi68** [nodeca/navit#39]
Would it be possible to add an option to choose the path to the PhantomJS executable?

I plan on using a version of PhantomJS that is compiled for Linux ARM and I won't be able to use the phantomjs-prebuilt module.

If it's not possible to add one, could you perhaps set me in the right direction so that I can specify my own location?

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/blob/3.0.2/lib/phantom/init.js#L22-L35

You can make PR with new option `enginePath` (and the same for electron).
