### ISSUE TITLE
Is there a way to `do.evaluate(fn)` ?

### ISSUE THREAD

**Issue by inca** [nodeca/navit#5]
Docs mentions `do.evaluate`, but it doesn't seem to exist. Is there a way to execute something on client without asserting or getting results?

Thanks.

**Comment by puzrin** [comment]
That seems to be a bug in readme. See `wait(fn)` https://github.com/nodeca/navit#actions-do (last). It should do exactly you need.

**Comment by inca** [comment]
Thanks, that does it.

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/blob/master/lib/get.js#L246

Seems we missed doc for `get.evaluate()`
