### ISSUE TITLE
Manipulating sub-document of an iframe

### ISSUE THREAD

**Issue by nylen** [nodeca/navit#8]
How can I call `.do.wait`, `.do.type` etc. using elements that appear inside of an `iframe` on the page?

**Comment by nylen** [comment]
well, this is ugly, but it seems to work:

``` js
browser
    // switch to child frame
    .fn(function() {
        browser.__page__.switchToFrame('contentarea');
    })
    .do.wait('#child_control')
    // switch back to main frame
    .fn(function() {
        browser.__page__.switchToMainFrame();
    })
```

**Comment by puzrin** [comment]
Do you think we need more simple iframe access or "public" page property instead of `__page__`? I could not find eqiuvalent in `nightmare` & `horseman` for iframe operations.

PS. Don't forget, you can always pack any custom commands as plugin package.

**Comment by nylen** [comment]
I've needed to do this before, but I agree it is not a common task so I suppose this way is good enough.  Hopefully this will help someone else who needs to descend into a child frame and perform operations in the context of its document instead :)

**Comment by puzrin** [comment]
Does it worth to create `frame.enter(selector)` and `frame.exit()` ? How ofter is this feature needed in your project tests?

**Comment by nylen** [comment]
@puzrin: For now I'm using `navit` to write browser scrapers against real sites rather than write tests.  Of course, I'd rather use a site's API if it has one.  Unfortunately many sites do not, and they are the same sites that are most likely to use frames because they are not very well-implemented (banks and other "enterprise" systems).

All that is to say... it would be very handy to my use cases to have `.frame.*` methods.  I think PhantomJS only supports getting a frame by its `name` attribute, though?

**Comment by puzrin** [comment]
> I think PhantomJS only supports getting a frame by its name attribute, though?

I didn't digged deep, but sure we can implement all requied addressing methods. If possible - try to suggest good method names, and i'll shedule those for nearest release. Sinse english is not my native language, the most difficult is to invent proper names for api methods :)

We can implement it soon, after finish our new project [tabex](https://github.com/nodeca/tabex).

**Comment by nylen** [comment]
I'd use `.frame.enter(selector)` and `.frame.top()`.  I haven't run across any other methods that I needed that weren't already there :)

**Comment by puzrin** [comment]
Isn't `.frame.top()` confusing? Intuitively looks like "scroll to top"

**Comment by nylen** [comment]
I said `top` because it is `window.top` in the DOM, but I think what you wrote, `.frame.exit()` is fine too.

**Comment by puzrin** [comment]
Done
